### ISSUE TITLE
Please cut new release

### ISSUE THREAD

**Issue by conorliv** [spindance/ten_thousand_feet#6]
@thillerson Please cut a new release of this gem with the new features that I added. I'd like to use the new features in my project, and don't want to release my own version of the gem if I don't have to. Thanks!

**Comment by conorliv** [comment]
@thillerson Could you please give me a sense of what you're thinking? I don't mind if you don't want to publish a new version of the gem, just let me know and I'll publish my own version. If you're planning to publish a new version but need some more time, please let me know what your timeline is looking like.

**Comment by thillerson** [comment]
@conorliv 

I’ve never done a release of the library, so I’m not sure what’s involved. I haven’t gotten the time in the last few days to look into it. With Kyle no longer at the company, we’re probably not in the best position to maintain this library. If you’re using it, would you like us to transfer it to you?

**Comment by conorliv** [comment]
@thillerson Thanks for your response, I appreciate it! I'll talk to my manager about it and get back to you early next week.

**Comment by conorliv** [comment]
@thillerson I talked to my manager and we decided that we'd like take on the role of maintaining this gem. Please transfer repo ownership to us. Thanks!

**Comment by conorliv** [comment]
Our Github organization is https://github.com/spindance

**Comment by thillerson** [comment]
I've requested to transfer to your username, you or someone with admin rights will have to move it to spindance.

**Comment by kylesuss** [comment]
Hey @conorliv , I added `rubygems@spindance.com` as an owner on the gem. Feel free to push up the new version.

**Comment by conorliv** [comment]
@kylesuss Great, thanks so much!

**Comment by thillerson** [comment]
Great, thanks Kyle. Conor, enjoy.
